### ISSUE TITLE
Load full Tibetan dataset into the database on the production server

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus#24]
@TrebuhD I gonna need some advice on how we can do this. My naive assumption now would be: Run docker on the xeon machine and use the async data loader, then copy the docker image with the loaded files over to our production server and replace the currently running image with the new one. Since you set the current setup on the server up, I guess it might be best if I copy over the docker image and leave the switching of the images to you, what do you think? Is there anything I am missing out here?

**Comment by TrebuhD** [comment]
It's an interesting idea, but I wouldn't exactly use this route. I think we have a few options here:

Option 1:
 All the database data is stored in a docker volume named `dbdata`. This means we could try to migrate the volume to another host, as described here:
- https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes
- https://stackoverflow.com/questions/21597463/how-to-port-data-only-volumes-from-one-host-to-another

2. We could use `arangodump` to dump and restore the database contents: https://www.arangodb.com/docs/3.3/administration-arangodump.html.

3. I could set the `dataloader` project, so that you run it on the Xeon machine, but it connects to the database instance on the remote server. It could take me some time though.

Options 1 & 2 are pretty similar, but I think the first one is cleaner. If you like the third option, I can describe it in more detail.

**Comment by sebastian-nehrdich** [comment]
I see & thank you for the feedback! I think option one makes most sense and I will look into that first. I guess I will then run docker & load the data on the Xeon machine and once that is finished, we transfer just the dbdata volume to the server, right? If I got it right, the setup of the database is now finished and we are just making modification/changes to the API at this stage, which is seperate from ArangoDB, so it's safe to start loading the full data into the database now, right? I guess we have to do that step by step - first the Tibetan, then the Chinese, Pali and so on.

**Comment by TrebuhD** [comment]
Sounds good to me! You can try loading all the files by removing the LIMIT env variable.
